name: Github Pages
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'labsyspharm/minerva-core-ui'
          path: minerva-core-ui 
          token: ${{ secrets.GH_AUTH_TOKEN }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install:
            cwd: minerva-core-ui
      - name: Build with pnpm
        run: |
          cd minerva-core-ui
          pnpm run pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: minerva-core-ui/dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
      contents: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4
        id: deployment
